### PR TITLE
[WEB-3581] Table migration

### PR DESCRIPTION
**Pull request by jamiehenson**
## Jira Ticket Link / Motivation

https://ably.atlassian.net/jira/software/projects/WEB/boards/172?selectedIssue=WEB-3581

## Summary of changes

This PR introduces the `Table` and `Tooltip` components into `ably-ui`, migrated from the [pricing page](https://ably.com/pricing) on Ably.com. Comparing to their original forms, the following changes have been made:

**Table**
- a restructuring from a single component that takes data props to an open set of stylised components for each of the constituent parts of a table (row, cell etc). This takes inspiration from [Radix's approach](https://www.radix-ui.com/themes/docs/components/table), Radix being a candidate for further adoption later on. Look at `PricingPageTable` in `src/core/Table/stories` for example of how these components are used.
- a switch from a `display: grid` structure to a semantic HTML structure. This is a personal choice, mainly from an accessibility and standards viewpoint - when displaying tabular data, we should use a `table`. Previous styling has been maintained as much as possible considering this change. 
- minor fixes have been made to spacings and alignments across different viewpoints.

Screenshot 2024-03-26 at 09 45 38

**Tooltip**
- this component has been split out from the Table for easier access and reuse.
- the component has been rewritten to eliminate the `floating-ui` dependency. My motivation here was that a) it didn't initially work in Storybook (undetermined reasons) and b) it wasn't difficult to recreate the functionality being used from `floating-ui` within the component. The tooltip can only render above the trigger and only takes into account the top and left window bounds - this can be extended later if other positionings are required.

## How do you manually test this?

Pull down and `yarn storybook`, check the `Table` and `Tooltip` stories. `Table` has a stripped out version of the pricing page table in there.

## Merge/Deploy Checklist

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

## Frontend Checklist

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

### CODE REVIEW

**Review by aleksandar-r — APPROVED** [review]
Code looks very clean, stories are highly performant. Well done @jamiehenson!

**Review by kennethkalmer — CHANGES_REQUESTED** [review]
This looks fantastic @jamiehenson, thank you so much 👏.

Small ask, could we change all copy from "Committed Use" to "Custom", just so it lines up with the pricing page updates that are in flight at the moment?

I also noticed this on smaller viewports and I'm not sure if it is intentional or not:

Table - Pricing Page ⋅ Storybook 2024-03-26 13-51-20

**Comment by jamiehenson** [comment]
@kennethkalmer sure thing - as for the gaps, there should be icons there 🤔 
Screenshot 2024-03-26 at 14 26 18

**Comment by kennethkalmer** [comment]
> @kennethkalmer sure thing - as for the gaps, there should be icons there 🤔 Would you mind hard-refreshing to double check?

Make sense, I just pulled down the updates and it worked just fine ¯\\\_(ツ)\_/¯

**Pull request merged**
