### PR TITLE
[EDX-402] Add new icons for sticky tabs

### PR DESCRIPTION
**Pull request by Nosfheratu**
Jira Ticket Link / Motivation
----
https://ably.atlassian.net/browse/EDX-402

Summary of changes
----
Just added new icons for the sticky nav. This PR is related to https://github.com/ably/voltaire/pull/499 and should be merged/deployed before than voltaire PR

How do you manually test this?
----

Reviewer Tasks (optional)
----

Merge/Deploy Checklist
----

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

Frontend Checklist
----

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

### CODE REVIEW

**Review by artismarti — APPROVED** [review]

**Review by artismarti — DISMISSED** [review]
Hey, @Nosfheratu the icons are not showing up correctly in the preview. Could you please check?

Thanks

**Comment by Nosfheratu** [comment]
> Hey, @Nosfheratu the icons are not showing up correctly in the preview. Could you please check?
> 
> 
> 
> Thanks

@artismarti  let me check

**Comment by dpiatek** [comment]
@artismarti @Nosfheratu does not have the permissions to release, so he can't build a preview, I'll check this locally

**Comment by dpiatek** [comment]
Released a preview app. Note I've also amended the SVG's so it's possible to add hover states and such:

Screenshot 2022-11-14 at 09 55 22

**Review by dpiatek — APPROVED** [review]

**Comment by Nosfheratu** [comment]
> @artismarti @Nosfheratu does not have the permissions to release, so he can't build a preview, I'll check this locally

@artismarti yeah i forgot to mention that i dont have permission to publish (sorry) but yeah, was showing in my local environment, thanks for notice that @dpiatek 

image

**Comment by Nosfheratu** [comment]
thanks everybody

**Pull request merged**
